# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Harikrish
tagline:          'A curious programmer'
description:      'A man who is hungry for solving problems and automating mundane
stuffs.'
url:              http://harikrish00.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
